<?php

namespace Modules\AiChatPanel\Providers;

use Illuminate\Support\ServiceProvider;

if (!defined('AICHATPANEL_MODULE')) {
    define('AICHATPANEL_MODULE', 'aichatpanel');
}

class AiChatPanelServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = false;

    /**
     * Container key set while the panel renders, read by
     * registerVendorScripts(). A container binding rather than a static: it is
     * scoped to the request that set it, which a static only is by accident of
     * php-fpm resetting between requests.
     */
    const PANEL_RENDERED = 'aichatpanel.panel_rendered';

    /**
     * Boot the application events.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerConfig();
        $this->registerViews();
        $this->loadMigrationsFrom(__DIR__.'/../Database/Migrations');

        $this->registerAssets();
        $this->registerVendorScripts();
        $this->registerSettings();
        $this->registerPanel();
        $this->registerCleanup();
        $this->registerChangeTracking();
        $this->registerSchedule();
    }

    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        // Modules use <locale>.json files keyed by the English string, which is
        // what loadJsonTranslationsFrom reads. It must run in register(), not
        // boot(), to be in place before the first __() call.
        $this->loadJsonTranslationsFrom(__DIR__.'/../Resources/lang');

        // One instance per request. The hooks in registerChangeTracking() fire
        // deep inside core's model layer and must reach the same object the
        // controller later reads.
        $this->app->singleton(\Modules\AiChatPanel\Services\ChangeCollector::class);

        if ($this->app->runningInConsole()) {
            $this->commands([
                \Modules\AiChatPanel\Console\PurgeCommand::class,
            ]);
        }
    }

    /**
     * Get the module's stylesheet and scripts into the layout.
     *
     * Only the scripts go through a filter now; the stylesheet is emitted
     * directly, see registerStylesheet(). Public/ is symlinked to
     * core/public/modules/<alias> by `php artisan freescout:module-install`,
     * so every path here is checked with file_exists() first: a missing symlink
     * must not produce a 404 on every page.
     *
     * @return void
     */
    protected function registerAssets()
    {
        // module.css deliberately does NOT go through the `stylesheets` filter.
        // See registerStylesheet() for why.
        $this->registerStylesheet();

        \Eventy::addFilter('javascripts', function ($javascripts) {
            // Only our own files go in here. The vendored renderer and
            // sanitiser must stay out of this list — see
            // registerVendorScripts() for why.
            //
            // vars.js is generated by `freescout:module-build aichatpanel`;
            // without it module.js falls back to the English source strings.
            $files = [
                '/js/vars.js',
                '/js/module.js',
            ];

            foreach ($files as $file) {
                $path = \Module::getPublicPath(AICHATPANEL_MODULE).$file;
                if (file_exists(public_path($path))) {
                    $javascripts[] = $path;
                }
            }

            return $javascripts;
        });
    }

    /**
     * module.css, as its own link tag outside the minified bundle.
     *
     * Core passes everything in the `stylesheets` filter to
     * Minify::stylesheet(), and devfactory/minify 1.0.7 (core composer.json)
     * predates CSS custom properties: it keeps a `--var: value` definition but
     * silently deletes every declaration that *consumes* one with var().
     *
     * The panel is positioned entirely through those four declarations, so on
     * any install that minifies, .aicp-panel came out as
     *
     *     .aicp-panel{position:fixed;right:0;z-index:999;display:none;...}
     *
     * with no top, bottom or width, and the layout rule next to it collapsed to
     * an empty body.aicp-open #conv-layout,...{} — the declaration was its only
     * content. The panel then opens at the foot of the document at full width,
     * which reads as "the panel does not open" because it is nowhere near the
     * viewport.
     *
     * A dev box hides it exactly the way it hid the marked bug:
     * config/minify.config.php lists `local` under ignore_environments, so each
     * file is served verbatim and the custom properties resolve.
     *
     * layout.head (core/resources/views/layouts/app.blade.php:21) renders above
     * core's Minify::stylesheet() call (:33), so our rules land before
     * style.css. That is safe here: everything in module.css is namespaced
     * .aicp-* / .aichatpanel-*, and the only core-owned targets are
     * body.aicp-open #conv-layout{,-header,-main} at specificity (0,1,1,1),
     * which outranks core's own (0,1,0,0) and .print (0,1,1,0) rules for those
     * ids no matter what order they are in.
     *
     * @return void
     */
    protected function registerStylesheet()
    {
        \Eventy::addAction('layout.head', function () {
            $path = \Module::getPublicPath(AICHATPANEL_MODULE).'/css/module.css';
            $full = public_path($path);

            if (!file_exists($full)) {
                return;
            }

            // asset() so the app still works installed in a subdirectory;
            // mtime so a module update is not served from a stale cache.
            echo '<link rel="stylesheet" href="'.e(asset($path).'?v='.filemtime($full)).'">'."\n";
        });
    }

    /**
     * marked and DOMPurify, as their own script tags outside the bundle.
     *
     * These must NOT go through the `javascripts` filter. Core passes that
     * whole list to Minify::javascript(), which concatenates every file and
     * runs JShrink over the result — and JShrink corrupts marked. It reads the
     * backticks inside marked's inline `text` regex as template-literal
     * delimiters, loses track of the regex, and strips the literal spaces out
     * of the rest of it:
     *
     *     /^(`+|[^`])(?:(?= {2,}\n)|...|[^ ](?= {2,}\n)))/   before
     *     /^(`+|[^`])(?:(?= {2,}\n)|...|[^](?={2,}\n)))/     after
     *
     * `[^]` followed by `{2,}` is "Nothing to repeat" — a SyntaxError. Since
     * the bundle is a single file, nothing in it parses: jQuery, Bootstrap and
     * main.js included. The navbar dies along with every other script on the
     * page, which is what this looks like from the outside.
     *
     * A dev box hides it. config/minify.config.php lists `local` under
     * ignore_environments, so with APP_ENV=local each file is served as its own
     * <script> tag and only marked itself breaks — the panel renders plain text
     * and everything else works.
     *
     * layout.body_bottom renders just above core's Minify::javascript() call
     * (core/resources/views/layouts/app.blade.php:278 vs :284), so both globals
     * are defined by the time module.js runs. CSP is script-src 'self' and
     * these are same-origin src attributes, so no nonce is involved.
     *
     * @return void
     */
    protected function registerVendorScripts()
    {
        \Eventy::addAction('layout.body_bottom', function () {
            // Only the conversation page mounts the panel, and these two are
            // 60 KB together — no reason to ship them with the mailbox list.
            if (!app()->bound(self::PANEL_RENDERED)) {
                return;
            }

            $files = [
                '/js/vendor/marked.min.js',
                '/js/vendor/purify.min.js',
            ];

            foreach ($files as $file) {
                $path = \Module::getPublicPath(AICHATPANEL_MODULE).$file;
                $full = public_path($path);

                if (!file_exists($full)) {
                    continue;
                }

                // asset() so the app still works installed in a subdirectory;
                // mtime so a module update is not served from a stale cache.
                echo '<script type="text/javascript" src="'.e(asset($path).'?v='.filemtime($full)).'"></script>'."\n";
            }
        });
    }

    /**
     * The panel itself: the toolbar toggle and the markup.
     *
     * @return void
     */
    protected function registerPanel()
    {
        // Toolbar toggle. conversation.get_action_buttons passes four
        // arguments, and every entry MUST have a 'permission' closure —
        // ConversationActionButtons.php:149 calls it unconditionally and an
        // entry without one takes the whole conversation page down.
        \Eventy::addFilter('conversation.get_action_buttons', function ($actions, $conversation, $user, $mailbox) {
            if (!\Modules\AiChatPanel\Services\Settings::isUsable($mailbox)) {
                return $actions;
            }

            $actions['aichatpanel'] = [
                'icon'       => 'glyphicon-comment',
                'location'   => \App\Misc\ConversationActionButtons::LOCATION_TOOLBAR,
                'label'      => __('AI Chat'),
                'class'      => 'aicp-toggle',
                'permission' => function ($conversation) use ($user) {
                    return $user && $user->can('view', $conversation);
                },
            ];

            return $actions;
        }, 20, 4);

        // Per-mailbox settings page, in the mailbox settings sidebar.
        \Eventy::addAction('mailboxes.settings.menu', function ($mailbox) {
            try {
                $user = auth()->user();

                if (!$user || !$mailbox || !$user->can('update', $mailbox)) {
                    return;
                }

                echo \View::make(AICHATPANEL_MODULE.'::partials.settings_menu', [
                    'mailbox' => $mailbox,
                ])->render();
            } catch (\Exception $e) {
                \Helper::logException($e, '[AiChatPanel] Rendering the mailbox settings menu failed: ');
            }
        }, 80, 1);

        // Panel markup. after_customer_sidebar takes one argument and, unlike
        // conversation.after_prev_convs, fires even when the conversation has
        // no customer.
        \Eventy::addAction('conversation.after_customer_sidebar', function ($conversation) {
            try {
                $user = auth()->user();

                if (!$user || !$conversation) {
                    return;
                }

                $mailbox = $conversation->mailbox;

                if (!\Modules\AiChatPanel\Services\Settings::isUsable($mailbox)) {
                    return;
                }

                // Server-side gate. The routes check this again per request;
                // this only decides whether to render anything at all.
                if (!$user->can('view', $conversation)) {
                    return;
                }

                $prefs = \Modules\AiChatPanel\Entities\UserPref::forUser($user->id);

                $shortcuts = \Modules\AiChatPanel\Services\Settings::get('prompt_shortcuts', $mailbox);

                if (!is_array($shortcuts)) {
                    $shortcuts = [];
                }

                // Let other modules contribute shortcuts.
                $context = new \Modules\AiChatPanel\Services\PanelContext($conversation, $user);
                $shortcuts = \Eventy::filter('aichatpanel.prompt_shortcuts', $shortcuts, $context);

                // Tells registerVendorScripts() to emit marked and DOMPurify.
                // This hook fires inside @yield('content'), which the layout
                // renders before @action('layout.body_bottom').
                app()->instance(self::PANEL_RENDERED, true);

                echo \View::make(AICHATPANEL_MODULE.'::panel', [
                    'conversation' => $conversation,
                    'shortcuts'    => is_array($shortcuts) ? $shortcuts : [],
                    'prefs'        => [
                        'open'  => (bool) $prefs->panel_open,
                        'width' => (int) $prefs->panel_width,
                    ],
                    // The panel decides Today/Yesterday itself, so it needs the
                    // same timezone the server formatted the messages in.
                    'timezone'     => $user->timezone ?: (config('app.timezone') ?: \App\User::DEFAULT_TIMEZONE),
                ])->render();
            } catch (\Exception $e) {
                // A broken panel must never take down the conversation page.
                \Helper::logException($e, '[AiChatPanel] Rendering the panel failed: ');
            }
        }, 20, 1);
    }

    /**
     * Delete our rows when a conversation goes.
     *
     * Both hooks are required. conversation.deleting only fires for a delete on
     * a model instance; the bulk path used by the UI deletes with a query and
     * says so itself in core/app/Conversation.php:2006 — "Observers do not
     * react on this kind of deleting."
     *
     * @return void
     */
    protected function registerCleanup()
    {
        \Eventy::addAction('conversation.deleting', function ($conversation) {
            if ($conversation) {
                \Modules\AiChatPanel\Entities\Chat::deleteForConversations([$conversation->id]);
            }
        }, 20, 1);

        \Eventy::addAction('conversations.before_delete_forever', function ($conversation_ids) {
            \Modules\AiChatPanel\Entities\Chat::deleteForConversations($conversation_ids);
        }, 20, 1);
    }

    /**
     * Notice what an AI turn changes in the conversation, so the page behind
     * the panel can update without a reload.
     *
     * These hooks fire on every request, including every incoming email — the
     * collector is inert until ChatController arms it, and each callback is
     * wrapped because a broken panel must never take down mail fetching.
     *
     * The argument counts differ per hook and Eventy defaults to 1, so they are
     * all stated explicitly. They are counted at the call site in core, not
     * taken from the docs.
     *
     * @return void
     */
    protected function registerChangeTracking()
    {
        // core/app/Observers/ThreadObserver.php:92. Fires for drafts and line
        // items too, which is the whole reason this is the right hook:
        // SetStatusTool calls Conversation::changeStatus() and never sees the
        // id of the line-item thread core creates inside it.
        \Eventy::addAction('thread.created', function ($thread) {
            try {
                \Modules\AiChatPanel\Services\ChangeCollector::instance()->noteThread($thread);
            } catch (\Exception $e) {
                \Helper::logException($e, '[AiChatPanel] Recording a created thread failed: ');
            }
        }, 20, 1);

        // core/app/Observers/ThreadObserver.php:102. UpdateDraftTool edits an
        // existing thread, so it never fires thread.created — without this the
        // rewritten draft would stay stale on the page until a reload.
        \Eventy::addAction('thread.updated', function ($thread) {
            try {
                \Modules\AiChatPanel\Services\ChangeCollector::instance()->noteThread($thread, true);
            } catch (\Exception $e) {
                \Helper::logException($e, '[AiChatPanel] Recording an updated thread failed: ');
            }
        }, 20, 1);

        // core/app/Conversation.php:1904 — four arguments.
        \Eventy::addAction('conversation.status_changed', function ($conversation, $user, $changed_on_reply, $prev_status) {
            try {
                \Modules\AiChatPanel\Services\ChangeCollector::instance()->noteConversation($conversation);
            } catch (\Exception $e) {
                \Helper::logException($e, '[AiChatPanel] Recording a status change failed: ');
            }
        }, 20, 4);

        // core/app/Conversation.php:1932 — three arguments.
        \Eventy::addAction('conversation.user_changed', function ($conversation, $user, $prev_user_id) {
            try {
                \Modules\AiChatPanel\Services\ChangeCollector::instance()->noteConversation($conversation);
            } catch (\Exception $e) {
                \Helper::logException($e, '[AiChatPanel] Recording an assignee change failed: ');
            }
        }, 20, 3);
    }

    /**
     * Retention.
     *
     * Note this is a FILTER, not an action, and it must return the schedule
     * (core/app/Console/Kernel.php:192).
     *
     * @return void
     */
    protected function registerSchedule()
    {
        \Eventy::addFilter('schedule', function ($schedule) {
            $schedule->command('aichatpanel:purge')
                ->dailyAt('03:20')
                ->withoutOverlapping();

            return $schedule;
        }, 20, 1);
    }

    /**
     * Global admin settings page.
     *
     * Persistence is handled by core: SettingsController::processSave()
     * iterates the keys returned by settings.section_settings and writes each
     * through \Option::set(), applying encrypt() where section_params says so.
     * We only have to declare the keys, the params and the view.
     *
     * @return void
     */
    protected function registerSettings()
    {
        \Eventy::addFilter('settings.sections', function ($sections) {
            $sections[AICHATPANEL_MODULE] = [
                'title' => __('AI Chat Panel'),
                'icon'  => 'comment',
                'order' => 700,
            ];

            return $sections;
        }, 30);

        \Eventy::addFilter('settings.section_settings', function ($settings, $section) {
            if ($section != AICHATPANEL_MODULE) {
                return $settings;
            }

            return \Modules\AiChatPanel\Services\Settings::sectionSettings();
        }, 20, 2);

        \Eventy::addFilter('settings.section_params', function ($params, $section) {
            if ($section != AICHATPANEL_MODULE) {
                return $params;
            }

            return \Modules\AiChatPanel\Services\Settings::sectionParams($params);
        }, 20, 2);

        \Eventy::addFilter('settings.view', function ($view, $section) {
            if ($section != AICHATPANEL_MODULE) {
                return $view;
            }

            return AICHATPANEL_MODULE.'::settings';
        }, 20, 2);

        // The API key is rendered masked. Without this, saving any other field
        // would persist the mask over the real key.
        \Eventy::addFilter('settings.before_save', function ($request, $section, $settings) {
            if ($section != AICHATPANEL_MODULE) {
                return $request;
            }

            return \Modules\AiChatPanel\Services\Settings::preserveMaskedSecrets($request);
        }, 20, 3);
    }

    /**
     * Register config.
     *
     * @return void
     */
    protected function registerConfig()
    {
        $this->publishes([
            __DIR__.'/../Config/config.php' => config_path(AICHATPANEL_MODULE.'.php'),
        ], 'config');

        $this->mergeConfigFrom(
            __DIR__.'/../Config/config.php', AICHATPANEL_MODULE
        );
    }

    /**
     * Register views.
     *
     * Published to resources/views/modules/<alias> so an installation can
     * override any of them without editing the module.
     *
     * @return void
     */
    public function registerViews()
    {
        $viewPath = resource_path('views/modules/'.AICHATPANEL_MODULE);
        $sourcePath = __DIR__.'/../Resources/views';

        $this->publishes([
            $sourcePath => $viewPath,
        ], 'views');

        $this->loadViewsFrom(array_merge(array_map(function ($path) {
            return $path.'/modules/'.AICHATPANEL_MODULE;
        }, \Config::get('view.paths')), [$sourcePath]), AICHATPANEL_MODULE);
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [];
    }
}
